---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:

  age-keygen:
    desc: Initialize Age Key for Sops
    cmd: age-keygen --output {{.AGE_FILE}}
    status: ["test -f {{.AGE_FILE}}"]

  encrypt:
    desc: Encrypt all Kubernetes SOPS secrets
    cmds:
      - cmd: |
          if [ ! -f {{.SOPS_CONFIG_FILE}} ]; then
            echo "Missing Sops config file"
            exit 1
          fi
          if [ ! -f {{.AGE_FILE}} ]; then
            echo "Missing Sops Age key file"
            exit 1
          fi
          find "{{.KUBERNETES_DIR}}" -type f -name "*.sops.*" | while read -r file; do
            if sops filestatus "$file" | jq --exit-status ".encrypted == false" > /dev/null; then
              sops --encrypt --in-place "$file"
              echo "Encrypted $file"
            fi
          done

  .reset:
    internal: true
    cmd: rm -rf {{.SOPS_CONFIG_FILE}}
